
import java.text.SimpleDateFormat;
import java.sql.*;
import Project.dbms;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.repo.Resource;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Nisal
 */
public class NewTransaction extends javax.swing.JFrame {

    /**
     * Creates new form issueBook
     */
    public static String Trans = "";

    public NewTransaction() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        if ("Librarian".equals(Login.Role)) {
            jButton2.setVisible(true);
            jTextField2.setVisible(true);
            jLabel4.setVisible(true);
        } else {
            jButton2.setVisible(false);
            jTextField2.setVisible(false);
            jLabel4.setVisible(false);
        }
        try {
            ResultSet rs = dbms.search("select * from transaction");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            String issueID = "";
            while (rs.next()) {
                String[] rows = {rs.getString("transactionID"), rs.getString("transactionDate"), rs.getString("fineAmount"),
                    rs.getString("dueDate"), rs.getString("resourceID"), rs.getString("userID"), rs.getString("studentID")};
                model.addRow(rows);
                issueID = rs.getString("transactionID");
            }
            if (!issueID.equals("")) {
                issueID = String.valueOf(Integer.parseInt(issueID) + 1);

                jTextField3.setText(issueID);
            } else {
                jTextField3.setText("1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }

        try {
            ResultSet rs = dbms.search("select * from student");
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                String[] rows = {rs.getString("studentID"), rs.getString("name"), rs.getString("guardianName"),
                    rs.getString("courseName"), rs.getString("contactNo"), rs.getString("registrationYear"), rs.getString("registrationFee")};
                model.addRow(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            ResultSet rs = dbms.search("select * from resource");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                String[] rows = {rs.getString("resourceID"), rs.getString("title"), rs.getString("author"),
                    rs.getString("category"), rs.getString("publishedYear"), rs.getString("price"), rs.getString("status")};
                model.addRow(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Resource ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 210, 74, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 160, 74, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Transaction ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 480, 80, -1));

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 150, 194, 25));

        jTextField2.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 470, 194, 25));

        jDateChooser2.setBackground(new java.awt.Color(255, 204, 204));
        jDateChooser2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooser2FocusLost(evt);
            }
        });
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 300, 194, 25));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Issue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 530, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Transaction ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, -1, 20));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 204, 204));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 100, 194, 25));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Transaction Date", "Fine Amount", "Due Date", "Resource ID", "User ID", "Student ID"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 80));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 290));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Guardian Name", "Course Name", "Contact No", "Registration Year", "Registration Fee"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 650, 290));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Resource ID", "Title", "Author", "Category", "Published Year", "Price", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 650, 290));

        jTextField4.setBackground(new java.awt.Color(255, 204, 204));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 200, 194, 25));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fine Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 380, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 204, 204));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 250, 194, 25));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Due Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 310, 74, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/books_flowers_blur_108950_1366x768.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String transactionID = jTextField2.getText();

        try {
            ResultSet rst = dbms.search("select * from transaction where transactionID='" + transactionID + "'");
            dbms.iud("delete from receipt where transactionID='" + transactionID + "'");
            try {

                rst.next();
                dbms.iud("UPDATE resource SET status = 'Available' WHERE status = 'Unavailable' and resourceID='" + rst.getString("resourceID") + "';");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e, "Book Status not updated", JOptionPane.ERROR_MESSAGE);
                setVisible(false);
                new NewTransaction().setVisible(true);
            }
            dbms.iud("DELETE from transaction WHERE transactionID = '" + transactionID + "'");
            JOptionPane.showMessageDialog(null, "Successfully Deleted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            setVisible(false);
            new NewTransaction().setVisible(true);
        }
        setVisible(false);
        new NewTransaction().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");

        String transactionID = jTextField3.getText();
        String studentID = jTextField1.getText();
        String resourceID = jTextField4.getText();
        String fineAmount = jTextField5.getText();
        String dueDate = dFormat.format(jDateChooser2.getDate());
        System.out.println(Date.valueOf(LocalDate.now()));

        try {
            ResultSet rs = dbms.search("select * from resource where resourceID='" + resourceID + "' and status='Unavailable'");
            ResultSet rsd = dbms.search("select * from transaction where studentID ='" + studentID + "'");
            if (rsd.next()) {
                JOptionPane.showMessageDialog(this, "This Student already borrowed a book", "Error", JOptionPane.ERROR_MESSAGE);
                new NewTransaction().setVisible(true);
            } else if (rs.next()) {
                JOptionPane.showMessageDialog(this, "This book is Unavailable", "Error", JOptionPane.ERROR_MESSAGE);
                new NewTransaction().setVisible(true);
            } else {
                dbms.iud("insert into transaction values('" + transactionID + "', '" + Date.valueOf(LocalDate.now()) + "', '" + fineAmount + "', '" + dueDate + "', '" + resourceID + "'" + ", '" + Login.ID + "', '" + studentID + "')");
                System.out.println("inserted transaction");
                dbms.iud("UPDATE resource SET status = 'Unavailable' WHERE resourceID = '" + resourceID + "' ");
                System.out.println("updated book");
                Trans = transactionID;
                ResultSet rst = dbms.search("select COALESCE(max(receiptID),0) from receipt");
                rst.next();
                dbms.iud("insert into receipt values('" + String.valueOf(Integer.parseInt(rst.getString(1)) + 1) + "','0','Issue','" + NewTransaction.Trans + "','" + Login.ID + "')");

                JOptionPane.showMessageDialog(null, "Successfully Updated");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error Transaction Form Issue Button", JOptionPane.ERROR_MESSAGE);
            setVisible(false);
            new NewTransaction().setVisible(true);
        }
        new IssuePannel().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        try {
            ResultSet rs = dbms.search("select * from student where studentID like  '%" + jTextField1.getText() + "%'");
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                String[] rows = {rs.getString("studentID"), rs.getString("name"), rs.getString("guardianName"),
                    rs.getString("courseName"), rs.getString("contactNo"), rs.getString("registrationYear"), rs.getString("registrationFee")};
                model.addRow(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        try {
            ResultSet rs = dbms.search("select * from resource where resourceID like  '%" + jTextField4.getText() + "%'");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                String[] rows = {rs.getString("resourceID"), rs.getString("title"), rs.getString("author"),
                    rs.getString("category"), rs.getString("publishedYear"), rs.getString("price"), rs.getString("status")};
                model.addRow(rows);

                if (rs.getString("category").equals("Books")) {
                    jTextField5.setText("20");
                }
                if (rs.getString("category").equals("Articles")) {
                    jTextField5.setText("15");
                }
                if (rs.getString("category").equals("Magazines")) {
                    jTextField5.setText("5");
                }
                if (jTextField4.getText().equals("")) {
                    jTextField5.setText("");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jDateChooser2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser2FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser2FocusLost

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
